# Site settings
title: 8thBit Laboratory
description: Indie game-dev studio
 baseurl: "/" # the subpath of your site, e.g. /blog
 url: "https://8tbl.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 8thBit Laboratory
user_description: I am Pavel Silin and I develop mobile games. Hope you will like it :)
user_title: Indie game-dev studio
email: 8thbitlab@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
