# Site settings
title: 8thBit Laboratory
description: Indie game-dev studio
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://8tbl.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 8thBit Laboratory
user_description: Hello, I am Pavel Silin - single indie-developer, and I develop mobile games. Hope you will like them :)
user_title: Indie game-dev studio
email: 8thbitlab@gmail.com
twitter_username: 8tbl1
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
